[package]
name = "jex-sc-staking-v2"
version = "0.0.0"
authors = [ "Aurélien Passion <aurelien.passion@gmail.com>",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.38.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
